### ISSUE TITLE
No feedback on Job Log action for `dead` job

### ISSUE THREAD

**Issue by davecharron** [codefori/vscode-db2i#204]
If your job connection gets snipped, and you then click the **View Job Log** action, there is no feedback to the user, so it looks like the action itself is broken.
There is output in the debug console:
```
rejected promise not handled within 1 second: Error: Not connected, , 0
extensionHostProcess.js:144
stack trace: Error: Not connected, , 0
	at _Query.<anonymous> (c:\Code\vscode-db2i\dist\extension.js:584:15)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Code\vscode-db2i\dist\extension.js:490:24)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
If instead you try to run a statement, there is at least some feedback, though not polished, posted to the IBM I view:
```Not connected, , 0```
Need to provide better feedback when a `dead` job is detected.

**Comment by worksofliam** [comment]
Perhaps `getStatus` needs to check the connection too?

**Comment by buzzia2001** [comment]
Fixed with new joblog view
