### ISSUE TITLE
SQL Trace for "getLargeUpdateCount not implemented"

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-db2i#237]
<details>
<summary>Trace</summary>

```
<html><body bgcolor="white">


<hr>
<b>[DATASTREAM_IN]: </b><i>2024-06-07.07.27.08.964</i>
<font color="DarkSlateGrey">
<blockquote>
<pre>
{"id":"id2","type":"connect","technique":"tcp","application":"vscode-db2i 1.0.0-dev","props":"libraries=SCHINDLN,QTEMP,OBJEKTTEST,DATEIEN,OBJEKTE,NEWSCAN,QGDDM,QIDU,QGPL,AUFTRAG,VERKAUF,EINKAUF,TAATOOL,ARCHIVP,GSESPL,E3SXROSS,E3SIROSS,SYSADMIN,SOURCEN,PROFOUNDUI,PROFOUNDJS,ILEASTIC,ILELDAP,ILEVATOR;naming=system;full open=false;transaction isolation=none;query optimize goal=1;block size=512;selfcodes=*NONE"}
</pre>
</blockquote>
</font>

<hr>
<b>[DATASTREAM_IN]: </b><i>2024-06-07.07.27.17.291</i>
<font color="DarkSlateGrey">
<blockquote>
<pre>
{"id":"id3","type":"setconfig","tracedest":"IN_MEM","tracelevel":"DATASTREAM"}
</pre>
</blockquote>
</font>

<hr>
<b>[DATASTREAM_OUT]: </b><i>2024-06-07.07.27.17.296</i>
<font color="DarkSlateBlue">
<blockquote>
<pre>
{"id":"id3","tracedest":"IN_MEM","tracelevel":"DATASTREAM","jtopentracedest":"IN_MEM","jtopentracelevel":"OFF","success":true}
</pre>
</blockquote>
</font>

<hr>
<b>[DATASTREAM_IN]: </b><i>2024-06-07.07.27.20.017</i>
<font color="DarkSlateGrey">
<blockquote>
<pre>
{"id":"query4","type":"sql","sql":"select * from qsys2.sysfuncs","terse":true,"rows":100}
</pre>
</blockquote>
</font>

<hr>
<b>[INFO]: </b><i>2024-06-07.07.27.20.017</i>
<font color="black">
<blockquote>
<pre>
asynchronously dispatcing a request of type: RunSql
</pre>
</blockquote>
</font>

<hr>
<b>[ERR]: </b><i>2024-06-07.07.27.20.351</i>
<font color="tomato">
<blockquote>
<pre>
java.lang.UnsupportedOperationException: getLargeUpdateCount not implemented
	at java.sql.Statement.getLargeUpdateCount(Statement.java:1103)
	at com.github.theprez.codefori.requests.RunSql.go(RunSql.java:24)
	at com.github.theprez.codefori.ClientRequest.run(ClientRequest.java:81)
	at java.lang.Thread.run(Thread.java:825)

</pre>
</blockquote>
</font>

<hr>
<b>[DATASTREAM_OUT]: </b><i>2024-06-07.07.27.20.351</i>
<font color="DarkSlateBlue">
<blockquote>
<pre>
{"id":"query4","has_results":true,"error":"getLargeUpdateCount not implemented","success":false}
</pre>
</blockquote>
</font>

<hr>
<b>[DATASTREAM_IN]: </b><i>2024-06-07.07.27.22.832</i>
<font color="DarkSlateGrey">
<blockquote>
<pre>
{"id":"id5","type":"gettracedata"}
</pre>
</blockquote>
</font>

<hr>
<b>[INFO]: </b><i>2024-06-07.07.27.22.833</i>
<font color="black">
<blockquote>
<pre>
synchronously dispatcing a request of type: GetTraceData
</pre>
</blockquote>
</font>
</body></html>
```

</details>

**Comment by NicolasSchindler** [comment]
@worksofliam @ThePrez if you need more information just hit me up. Thanks already

**Comment by thisisole** [comment]
Hey @ThePrez, any news on this?  Unfortunately, we are still unable to use the plugin :(

**Comment by SanjulaGanepola** [comment]
@NicolasSchindler @thisisole Is this still an issue?

**Comment by thisisole** [comment]
No
